title = "Anderson Optimization"
baseURL = "https://andersonoptimization.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Service"
    url = "/service"
  [[menu.header]]
    weight = 3
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 4
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Power System Modeling &amp Optimization"
    subtitle = "Novel renewable siting and grid modeling software that delivers results faster and more accurately than traditional solutions."

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Why Anderson Optimization"
    bullet1 = "Enhanced Modeling Capabilities"
    content1 = "Other solutions often use dated models built for historical power systems. We utilize the latest optimization research to provide software designed specifically for modern energy grids with significant uncertainty from renewables and storage."
    bullet2 = "Cloud-Based Software"
    content2 = "Our cloud-based infrastructure provides scalable computing power so users can run more simulations and generate results faster."
    bullet3 = "Data Visualization"
    content3 = "We make results accessible to a broad base of users by providing outputs through clear data visualizations so that any user can quickly gain valuable insights."
    bullet4 = "Scenario Analysis"
    content4 = "We empower users to easily simulate any number of scenarios to determine the value and optimal project strategies."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "Optimize Your Business."
    paragraph = "No matter your situation, we'd love to hear from you. With our exceptional technical experience, we are confident that we can deliver a solution that best meets your needs."
    [params.call.button]
      caption = "Learn More"
      url = "#"
      text = "Learn More"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "1877 Broadway, Suite #100, Boulder, CO 80302"
      email = "Email: jake@andersonopt.com"
      email2 = "Email: eric@andersonopt.com"
      phone = "Phone: 612 719 5173"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
