title = "Anderson Optimization"
baseURL = "https://website.andersonopt.com/"
languageCode = "en-us"
theme = "airspace-hugo"


[menu]

  [[menu.header]]
    weight = 2
    name = "Solutions"
    url = "/service"
    class = "test"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 4
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "User Documentation"
    url = "https://docs.andersonopt.com/app/v3/"
  [[menu.footer]]
    weight = 2
    name = "Developer Documentation"
    url = "/developer/"
  

[taxonomies]
tag = "tags"
category = "categories"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.login]
  	name = "Client Login"
  	url = "https://v3.andersonopt.com"

  [params.slider]
    enable = true
    title = "Power System Modeling & Optimization"
    subtitle = "Renewable siting and grid modeling software that delivers results faster and more accurately than traditional solutions."

  [params.wrapper]
    enable = true
    title = "Our Approach"
    italic = "We utilize over a decade of cutting-edge power system modeling, optimization research, and industry experience to deliver the best solution to every customer."
    paragraph = "We provide a core suite of software tools along with customization and new feature development services to ensure that our solutions best meet users’ needs while seamlessly integrating into their existing workflows. Our additional consultative services further ensure that clients attain maximum value from our software."    
    [params.wrapper.button]
      caption = "About Us"
      url = "about/"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Why Anderson Optimization?"
    bullet1 = "Enhanced Modeling Capabilities"
    content1 = "Utilize the latest optimization research to properly model modern energy grids with significant uncertainty from renewables and storage unlike other modeling tools built for stable, historical power systems."
    bullet2 = "Cloud-Based Software"
    content2 = "Attain scalable computing power to run more simulations and produce results faster."
    bullet3 = "Data Visualization"
    content3 = "Generate clear data visualizations make results more accessible to a broader base of users so that anyone can quickly gain valuable insights."
    bullet4 = "Scenario Analysis"
    content4 = "Easily simulate any number of scenarios to determine the value and optimal strategies for any project."


  [params.call]
    enable = true
    title = "Optimize Your Business."
    paragraph = "No matter your situation, we'd love to hear from you. We are confident that our team of experts can deliver the solution that best meets your needs."
    [params.call.button]
      caption = "Contact Us"
      url = "contact"
      text = "Contact Us"


  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "1877 Broadway, Suite #100, Boulder, CO 80302"
      email = "Email: jake@andersonopt.com"
      email2 = "Email: eric@andersonopt.com"
      phone = "Phone: 612 719 5173"
    [params.contact.gmaps]
      title = "Boulder Location"