title = "Anderson Optimization"
baseURL = "https://website.andersonopt.com/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Services"
    url = "/service"
    class = "test"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 4
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "User Documentation"
    url = "https://docs.andersonopt.com/app/v3/"
  [[menu.footer]]
    weight = 2
    name = "Developer Documentation"
    url = "/developer/"
  [[menu.footer]]
    weight = 3
    name = "Contact us"
    url = "/contact/"
  [[menu.footer]]
    weight = 4
    name = "How it works"
    url = "/service/"  

[taxonomies]
tag = "tags"
category = "categories"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.login]
  	name = "Client Login"
  	url = "https://v3.andersonopt.com"

  [params.slider]
    enable = true
    title = "Power System Modeling & Optimization"
    subtitle = "Novel renewable siting and grid modeling software that delivers results faster and more accurately than traditional solutions."

  [params.wrapper]
    enable = true
    title = "Our Approach"
    italic = "We utilize over a decade of cutting-edge power system modeling and optimization research and industry experience to deliver the best solution to every customer."
    paragraph = "We provide a core suite of software tools along with customization and new feature development services to ensure that our solutions best meet users’ needs while seamlessly integrating into their existing workflows. Our complementary consultative services further ensure that clients attain maximum value from our software."    
    [params.wrapper.button]
      caption = "About Us"
      url = "/about/"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Why Anderson Optimization?"
    bullet1 = "Enhanced Modeling Capabilities"
    content1 = "Utilize the latest optimization research to properly model modern energy grids with significant uncertainty from renewables and storage unlike other modeling tools built for stable, historical power systems."
    bullet2 = "Cloud-Based Software"
    content2 = "Scalable computing power to run more simulations and generate results faster."
    bullet3 = "Data Visualization"
    content3 = "Clear data visualizations make results more accessible to a broader base of users so that anyone can quickly gain valuable insights."
    bullet4 = "Scenario Analysis"
    content4 = "Easily simulate any number of scenarios to determine the value and optimal strategies for any project."


  [params.call]
    enable = true
    title = "Optimize Your Business."
    paragraph = "No matter your situation, we'd love to hear from you. With our exceptional technical experience, we are confident that we can deliver a solution that best meets your needs."
    [params.call.button]
      caption = "Learn More"
      url = "/contact"
      text = "Learn More"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "1877 Broadway, Suite #100, Boulder, CO 80302"
      email = "Email: jake@andersonopt.com"
      email2 = "Email: eric@andersonopt.com"
      phone = "Phone: 612 719 5173"
    [params.contact.gmaps]
      title = "Boulder Location"

  [params.about]
    enable = true
    name1 = "Eric Anderson, Ph.D."
    role1 = "Head of Technology"
    bio1 = "Eric obtained his Ph.D in Industrial Engineering in 2015 for his research in power system modeling and optimization. His research was focused on modeling uncertainty due to renewable generation and large scale computational experiments. After attaining his degree, he worked for a production cost modeling firm, Ascend Analytics, where he gained experience building production cost models incorporating the complexities of modern systems with renewable generation, complicated river and dam systems, energy storage, and uncertainty. At Anderson Optimization, Eric oversees all modeling, optimization, and software development initiatives as well as any other technical tasks."   
    name2 = "Jake Anderson"
    role2 = "Head of Business"
    headshot1 = "/img/eric-headshot.jpg"
    bio2 = "Jake comes from a Fortune 500 corporate finance background. During this time, Jake led a wide variety of project teams across numerous operating units. He consistently managed $100MM+ P&Ls and provided valuable strategic leadership to help meet corporate goals. He previously attained degrees in Finance and Entrepreneurial Management with a minor focus in Information System Management. Jake oversees all business management and sales activities for Anderson Optimization."
    headshot2 = "/img/jake-headshot.jpg"
    