baseurl = ""
description = ""
enableGitInfo = true
enableRobotsTXT = true
paginate = 7
title = "Anderson Optimization"
[blackfriday]
fractions = false
[params]
author = ""
email = ""
url = ""
ga_analytics = "UA-1179030-2"
ga_verify = "ZaNNn0hSVhEblnb4DBJ2Fvx6ZH3Baoa6zSkGmFkDqrU"
image = "random.jpg"
logo = "opt-logo.svg"
[taxonomies]
  tag = "tags"
[markup.goldmark.renderer]
unsafe= true
