version: 2
jobs:
  build:
    docker:
      - image: kshcherban/docker-hugo-awscli:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
      HUGO_BRANCH_BUILD_DIR: ~/hugo/branch-public
    steps:
      - checkout
      # install git
      # - run: apt-get update && apt-get install -y git && apt-get install -y software-properties-common

      # - run:
      #     name: install AWS CLI (first install pip, the Python package manager)
      #     command: |
      #       apt-get install -y python-pip
      #       pip install virtualenv virtualenvwrapper
      #       virtualenv venv
      #       source venv/bin/activate
      #       ls
      #       pip install -r requirements/dev.txt


      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init


      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      # build with Hugo
      - run: 
          command: |
            BASE_URL="https://andersonoptimization.com/"
            BRANCH_URL="http://website.andersonopt.com.s3-website-us-west-2.amazonaws.com/${CIRCLE_BRANCH}/"
            sed -i "s,$BASE_URL,$BRANCH_URL," config.toml
            HUGO_ENV=production hugo -v -d $HUGO_BRANCH_BUILD_DIR
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://website.andersonoptimization.com/latest --delete --acl=public-read --cache-control max-age=3600
            else
              echo "Not master branch, dry run only"
              aws s3 sync $HUGO_BRANCH_BUILD_DIR \
              s3://website.andersonopt.com/${CIRCLE_BRANCH}/ --delete --acl=public-read --cache-control max-age=60
            fi