version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
      HUGO_BRANCH_BUILD_DIR: ~/hugo/branch-public
    steps:

      # install git
      - run: apk update && apk add git

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli

      # - restore_cache:
      #     keys:
      #       - source-v1-{{ .Branch }}-{{ .Revision }}
      #       - source-v1-{{ .Branch }}-
      #       - source-v1-

      # checkout the repository
      - checkout

      # - save_cache:
      #   key: source-v1-{{ .Branch }}-{{ .Revision }}
      #   paths:
      #       - ".git"

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init


      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      # build with Hugo
      - run: BASE_URL="https://website.andersonopt.com/"; \
        BRANCH_URL="http://website.andersonopt.com.s3-website-us-west-2.amazonaws.com/${CIRCLE_BRANCH}";\
        sed -i "s,$BASE_URL,$NEW_URL," config.toml;
        HUGO_ENV=production hugo -v -d $HUGO_BRANCH_BUILD_DIR
 
 
      # - run:
      #     name: test our generated HTML files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy 
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://website.andersonopt.com/latest/ --delete --acl=public-read --cache-control max-age=60 --size-only
            else
              echo "Not master branch, dry run only"
              aws s3 sync $HUGO_BRANCH_BUILD_DIR \
              s3://website.andersonopt.com/${CIRCLE_BRANCH}/ --delete --acl=public-read --cache-control max-age=60 --size-only
            fi