---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/founders.yaml
  label: Founders
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/solutions
  label: Solutions
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "./*.md"
- type: heading
  label: Navigation
- type: document
  path: data/menu.yaml
  label: Menu
- type: document
  path: data/footer.yaml
  label: Footer
- type: heading
  label: Data
- type: directory
  path: data/support
  label: Support
  create: all
  match: "*.yaml"
- type: document
  path: data/testimonials.yaml
  label: Testimonials
- type: document
  path: data/authors.yaml
  label: Authors
- type: document
  path: data/partners.yaml
  label: Partners
- type: heading
  label: Misc
- type: directory
  path: data
  label: Data
  create: all
  match: "*.yaml"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.62.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.62.0
